[platformio]
; point data_dir to nonexistent directory so that PIO doesn't bother building SPIFFS
data_dir = nonexistent
default_envs = esp32-c3

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200

custom_nanopb_protos =
    +<**/*.proto>
custom_nanopb_options =
    --error-on-unmatched

extra_scripts =
    pre:pio_tools/gen_data.py

build_flags =
  ; BMS UART uses hardware Serial (UART0), not the native USB-CDC port.
  -DARDUINO_USB_CDC_ON_BOOT=0
  ;-DDEBUG_ESP_PORT=Serial

lib_deps =
    ottowinter/ESPAsyncWebServer-esphome@^3.0.0
    nanopb/Nanopb@^0.4.7
    bblanchon/ArduinoJson@^6.20.0

[env:ota]
extends = env:esp32-c3
extra_scripts =
    pre:pio_tools/gen_data.py
    pio_tools/platformio_upload.py
custom_upload_url = http://owie-c024.lan/update
upload_protocol = custom

[env:native]
platform = native
debug_test = test_battery_fuel_gauge
